
############################# 访问路径、端口tomcat start #############################
server:
  port: 8888
  servlet:
    context-path: /api
  tomcat:
    max-threads: 1000
    min-spare-threads: 30
    uri-encoding: UTF-8
############################# 访问路径、端口tomcat end ###############################

# 当前项目maven激活环境，例如：dev/test/uat/prod，对应pom.xml中profile设置值
---
spring:
  application:
    name: my-demo
  profiles:
    active: @profileActive@
  aop:
    auto: true
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8082

logging:
  config: classpath:config/log4j2.xml

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

  # 让 Sentinel 客户端知道去 zookeeper 中拿配置规则
sentinel:
  zookeeper:
    address: 127.0.0.1:2181
    path: /Sentinel/my-demo